-- This SQL script creates the tables needed for the project.

-- income table
CREATE TABLE income (
    _Any INT NOT NULL,
    Codi_Districte INT NOT NULL,
    Nom_Districte VARCHAR(255) NOT NULL,
    Codi_Barri INT NOT NULL,
    Nom_Barri VARCHAR(255) NOT NULL,
    Seccio_Censal VARCHAR NOT NULL,
    Import_Euros FLOAT NOT NULL,
    CONSTRAINT pk_income PRIMARY KEY (_Any, Seccio_Censal)
);

-- bicycle lanes table
CREATE TABLE bicycle_lanes (
    CODI_CAPA VARCHAR,
    CODI_SUBCAPA VARCHAR,
    ID VARCHAR,
    TOOLTIP VARCHAR,
    geometry GEOMETRY(LINESTRING, 4326),
    CONSTRAINT pk_bicycle_lanes PRIMARY KEY (ID)
);

-- bicycle station information table
CREATE TABLE bicycle_station_information (
    station_id INTEGER NOT NULL,
    name VARCHAR NOT NULL,
    physical_configuration VARCHAR NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL,
    altitude DOUBLE PRECISION,
    address VARCHAR NOT NULL,
    cross_street VARCHAR,
    post_code VARCHAR NOT NULL,
    capacity INTEGER NOT NULL,
    is_charging_station BOOLEAN NOT NULL,
    short_name INTEGER NOT NULL,
    nearby_distance INTEGER NOT NULL,
    x_ride_code_support BOOLEAN NOT NULL,
    rental_uris DOUBLE PRECISION,
    is_valet_station VARCHAR,
    last_updated INTEGER NOT NULL,
    ttl INTEGER NOT NULL,
    V1 DOUBLE PRECISION,
    CONSTRAINT station_inf_id_last_updated_pk PRIMARY KEY (station_id, last_updated)
);

-- bicycle station status table
CREATE TABLE bicycle_station_status (
    station_id INTEGER,
    num_bikes_available INTEGER NOT NULL,
    "num_bikes_available_types.mechanical" INTEGER NOT NULL,
    "num_bikes_available_types.ebike" INTEGER NOT NULL,
    num_docks_available INTEGER NOT NULL,
    last_reported INTEGER NOT NULL,
    is_charging_station BOOLEAN NOT NULL,
    status VARCHAR NOT NULL,
    is_installed INTEGER NOT NULL,
    is_renting INTEGER NOT NULL,
    is_returning INTEGER NOT NULL,
    traffic DOUBLE PRECISION,
    last_updated INTEGER,
    ttl INTEGER NOT NULL,
    V1 DOUBLE PRECISION,
    CONSTRAINT station_status_id_last_updated_pk PRIMARY KEY (station_id, last_updated)
);

-- population table
CREATE TABLE population (
    Data_Referencia VARCHAR NOT NULL NOT NULL,
    Codi_Districte VARCHAR NOT NULL NOT NULL,
    Nom_Districte VARCHAR NOT NULL NOT NULL,
    Codi_Barri VARCHAR NOT NULL NOT NULL,
    Nom_Barri VARCHAR NOT NULL NOT NULL,
    AEB VARCHAR NOT NULL NOT NULL,
    Seccio_Censal VARCHAR NOT NULL NOT NULL,
    Valor INTEGER NOT NULL,
    PRIMARY KEY (Data_Referencia, Seccio_Censal)
);

-- district table
CREATE TABLE district (
    ID_ANNEX        VARCHAR NOT NULL,
    ANNEXDESCR      VARCHAR NOT NULL,
    ID_TEMA         VARCHAR NOT NULL,
    TEMA_DESCR      VARCHAR NOT NULL,
    ID_CONJUNT      VARCHAR NOT NULL,
    CONJ_DESCR      VARCHAR NOT NULL,
    ID_SUBCONJ      VARCHAR NOT NULL,
    SCONJ_DESC      VARCHAR NOT NULL,
    ID_ELEMENT      VARCHAR NOT NULL,
    ELEM_DESCR      VARCHAR NOT NULL,
    NIVELL          VARCHAR NOT NULL,
    NDESCR_CA       VARCHAR NOT NULL,
    NDESCR_ES       VARCHAR NOT NULL,
    NDESCR_EN       VARCHAR NOT NULL,
    TERME           VARCHAR NOT NULL,
    DISTRICTE       VARCHAR,
    BARRI           VARCHAR NOT NULL,
    AEB             VARCHAR NOT NULL,
    SEC_CENS        VARCHAR NOT NULL,
    GRANBARRI       VARCHAR NOT NULL,
    ZUA             VARCHAR NOT NULL,
    AREA_I          VARCHAR NOT NULL,
    LITERAL         VARCHAR NOT NULL,
    PERIMETRE       NUMERIC NOT NULL,
    AREA            NUMERIC NOT NULL,
    ORD_REPRES      VARCHAR NOT NULL,
    CODI_UA         VARCHAR NOT NULL,
    TIPUS_UA        VARCHAR NOT NULL,
    NOM             VARCHAR NOT NULL,
    WEB1            VARCHAR NOT NULL,
    WEB2            VARCHAR NOT NULL,
    WEB3            VARCHAR NOT NULL,
    DOCUMENTA       VARCHAR NOT NULL,
    RANGESCALA      VARCHAR NOT NULL,
    TIPUS_POL       VARCHAR NOT NULL,
    GRUIX_ID        VARCHAR NOT NULL,
    GRUIXDIMEN      VARCHAR NOT NULL,
    ESTIL_ID        VARCHAR NOT NULL,
    ESTIL_QGIS      VARCHAR NOT NULL,
    VALOR1QGIS      VARCHAR NOT NULL,
    VALOR2QGIS      VARCHAR NOT NULL,
    COL_FARCIT      VARCHAR NOT NULL,
    FCOL_DESCR      VARCHAR NOT NULL,
    FHEX_COLOR      VARCHAR NOT NULL,
    COL_DESCR       VARCHAR NOT NULL,
    HEX_COLOR7      VARCHAR NOT NULL,
    geometry        geometry(Polygon,4326) NOT NULL,
    PRIMARY KEY (DISTRICTE)
);

-- neighbourhood table
CREATE TABLE neighbourhood (
    ID_ANNEX        VARCHAR NOT NULL,
    ANNEXDESCR      VARCHAR NOT NULL,
    ID_TEMA         VARCHAR NOT NULL,
    TEMA_DESCR      VARCHAR NOT NULL,
    ID_CONJUNT      VARCHAR NOT NULL,
    CONJ_DESCR      VARCHAR NOT NULL,
    ID_SUBCONJ      VARCHAR NOT NULL,
    SCONJ_DESC      VARCHAR NOT NULL,
    ID_ELEMENT      VARCHAR NOT NULL,
    ELEM_DESCR      VARCHAR NOT NULL,
    NIVELL          VARCHAR NOT NULL,
    NDESCR_CA       VARCHAR NOT NULL,
    NDESCR_ES       VARCHAR NOT NULL,
    NDESCR_EN       VARCHAR NOT NULL,
    TERME           VARCHAR NOT NULL,
    DISTRICTE       VARCHAR NOT NULL,
    BARRI           VARCHAR,
    AEB             VARCHAR NOT NULL,
    SEC_CENS        VARCHAR NOT NULL,
    GRANBARRI       VARCHAR NOT NULL,
    ZUA             VARCHAR NOT NULL,
    AREA_I          VARCHAR NOT NULL,
    LITERAL         VARCHAR NOT NULL,
    PERIMETRE       NUMERIC NOT NULL,
    AREA            NUMERIC NOT NULL,
    ORD_REPRES      VARCHAR NOT NULL,
    CODI_UA         VARCHAR NOT NULL,
    TIPUS_UA        VARCHAR NOT NULL,
    NOM             VARCHAR NOT NULL,
    WEB1            VARCHAR NOT NULL,
    WEB2            VARCHAR NOT NULL,
    WEB3            VARCHAR NOT NULL,
    DOCUMENTA       VARCHAR NOT NULL,
    RANGESCALA      VARCHAR NOT NULL,
    TIPUS_POL       VARCHAR NOT NULL,
    GRUIX_ID        VARCHAR NOT NULL,
    GRUIXDIMEN      VARCHAR NOT NULL,
    ESTIL_ID        VARCHAR NOT NULL,
    ESTIL_QGIS      VARCHAR NOT NULL,
    VALOR1QGIS      VARCHAR NOT NULL,
    VALOR2QGIS      VARCHAR NOT NULL,
    COL_FARCIT      VARCHAR NOT NULL,
    FCOL_DESCR      VARCHAR NOT NULL,
    FHEX_COLOR      VARCHAR NOT NULL,
    COL_DESCR       VARCHAR NOT NULL,
    HEX_COLOR7      VARCHAR NOT NULL,
    geometry        geometry(Polygon,4326) NOT NULL,
    PRIMARY KEY (BARRI)
);


-- census_tract table
CREATE TABLE census_tract (
    ID_ANNEX        VARCHAR NOT NULL,
    ANNEXDESCR      VARCHAR NOT NULL,
    ID_TEMA         VARCHAR NOT NULL,
    TEMA_DESCR      VARCHAR NOT NULL,
    ID_CONJUNT      VARCHAR NOT NULL,
    CONJ_DESCR      VARCHAR NOT NULL,
    ID_SUBCONJ      VARCHAR NOT NULL,
    SCONJ_DESC      VARCHAR NOT NULL,
    ID_ELEMENT      VARCHAR NOT NULL,
    ELEM_DESCR      VARCHAR NOT NULL,
    NIVELL          VARCHAR NOT NULL,
    NDESCR_CA       VARCHAR NOT NULL,
    NDESCR_ES       VARCHAR NOT NULL,
    NDESCR_EN       VARCHAR NOT NULL,
    TERME           VARCHAR NOT NULL,
    DISTRICTE       VARCHAR,
    BARRI           VARCHAR NOT NULL,
    AEB             VARCHAR NOT NULL,
    SEC_CENS        VARCHAR,
    GRANBARRI       VARCHAR NOT NULL,
    ZUA             VARCHAR NOT NULL,
    AREA_I          VARCHAR NOT NULL,
    LITERAL         VARCHAR NOT NULL,
    PERIMETRE       NUMERIC NOT NULL,
    AREA            NUMERIC NOT NULL,
    ORD_REPRES      VARCHAR NOT NULL,
    CODI_UA         VARCHAR NOT NULL,
    TIPUS_UA        VARCHAR NOT NULL,
    NOM             VARCHAR NOT NULL,
    WEB1            VARCHAR NOT NULL,
    WEB2            VARCHAR NOT NULL,
    WEB3            VARCHAR NOT NULL,
    DOCUMENTA       VARCHAR NOT NULL,
    RANGESCALA      VARCHAR NOT NULL,
    TIPUS_POL       VARCHAR NOT NULL,
    GRUIX_ID        VARCHAR NOT NULL,
    GRUIXDIMEN      VARCHAR NOT NULL,
    ESTIL_ID        VARCHAR NOT NULL,
    ESTIL_QGIS      VARCHAR NOT NULL,
    VALOR1QGIS      VARCHAR NOT NULL,
    VALOR2QGIS      VARCHAR NOT NULL,
    COL_FARCIT      VARCHAR NOT NULL,
    FCOL_DESCR      VARCHAR NOT NULL,
    FHEX_COLOR      VARCHAR NOT NULL,
    COL_DESCR       VARCHAR NOT NULL,
    HEX_COLOR7      VARCHAR NOT NULL,
    geometry        geometry(Polygon,4326) NOT NULL,
    PRIMARY KEY (DISTRICTE, SEC_CENS)
);

